
name: Custom Node.js CI and Angular

on:
  push:
    branches: [main] [master]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: echo "Hello from GitHub Actions!"
